version: '3.8'

services:
  php-fpm:
    build:
      context: .
    container_name: php-fpm
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads
    expose:
      - 9000
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=covago
    depends_on:
      - mysql
    entrypoint: ["sh", "-c", "while ! mysqladmin ping -h mysql --silent; do echo 'waiting for mysql'; sleep 2; done && php-fpm"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/var/www/html/uploads
    depends_on:
      - php-fpm

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: covago
    volumes:
      - db_data:/var/lib/mysql
      - ./covago.sql:/docker-entrypoint-initdb.d/covago.sql
    ports:
      - "3307:3306"

volumes:
  db_data:
